name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd /var/www/nuii/ai-assistant
            git reset --hard origin/main
            git clean -fd
            git pull origin main

            echo "Contents of $(pwd):"
            ls -la

            if [ -f package.json ]; then
              bun install
            else
              echo "❌ package.json not found; aborting"
              exit 1
            fi

            rm -rf .next
            bun run build
            pm2 restart ai-assistant

      - name: Notify Success
        if: success()
        run: echo "🚀 Deployment was successful"
